### ISSUE TITLE
Just clarifying question, not really an issue

### ISSUE THREAD

**Issue by ghost** [mrjackyliang/transmission-vpn#1]
Hi, I have just found that scrip and found it seems to be what I looked for. But I want to get some more info.
Is that scrip directing only transmission traffic via VPN and the rest of internet traffic on Synology is going without VPN? If yes that I am home ;-).

**Comment by mrjackyliang** [comment]
Hi @eskimos2000, sorry for the late reply. The script does what you want. Basically, it controls the Synology VPN, and Transmission. In between the lines, it controls whether or not the VPN is working and makes decisions whether to shut it off.

Generally, when the script is set up properly and assuming the VPN is disconnected, Transmission won't work anyways. Although, the main purpose of the script is to reconnect the VPN and reboot Transmission if it doesn't work.

**Comment by ghost** [comment]
No worries, thanks, that's what I needed.  Nice script man.

**Comment by mrjackyliang** [comment]
Thanks!!
