### ISSUE TITLE
Transmission wont start & Permission Issues

### ISSUE THREAD

**Issue by neek0la** [mrjackyliang/transmission-vpn#2]
I seem to get this output. when trying to install

`sudo sh transmissionvpn.sh install`

`Installing ...`
`package transmission stop successfully`
`Binding IPv4 Home Address ...`
`chown: invalid user: vc-transmission:root`
`Failed to start package 272`
`Installed!`

**Comment by mrjackyliang** [comment]
It seems like the user is supposed to be `svc-transmission`. Going to check on my side. See what's going on.

**Comment by mrjackyliang** [comment]
Seems like everything is running fine for me.

**Comment by mrjackyliang** [comment]
I did an update earlier and found some changes possibly related to the user and group change. Tested this on `DSM 6.1`.
