### ISSUE TITLE
Permission Issues and Port Forwarding Questions

### ISSUE THREAD

**Issue by MartynWilliams** [mrjackyliang/transmission-vpn#3]
Hi,

I get the following errors when executing the script
user : admin

path 
/volume1/downloads/Transmission/transmission-home 
sh transmission-vpn.sh start

**Install command** 

chown: changing ownership of ‘/volume1/downloads/Transmission/transmission-home/                                                 settings.json.bak’: Operation not permitted
package transmission start successfully
Installed!

**Uninstall**

admin@DiskStation:/volume1/downloads/Transmission/transmission-home$ sh transmission-vpn.sh uninstall
Uninstalling ...
Failed to stop package 273
Binding IPv4 Default Address ...
chown: changing ownership of ‘/volume1/downloads/Transmission/transmission-home/settings.json.bak’: Operation not permitted
package transmission start successfully
Uninstalled!

admin@DiskStation:/volume1/downloads/Transmission/transmission-home$ 
sh transmission-vpn.sh start

VPN is connecting ...
transmission-vpn.sh: line 40: /usr/syno/etc/synovpnclient/vpnc_connecting: Permission denied
transmission-vpn.sh: line 41: /usr/syno/etc/synovpnclient/vpnc_connecting: Permission denied
transmission-vpn.sh: line 42: /usr/syno/etc/synovpnclient/vpnc_connecting: Permission denied

get arguemnt protocol: openvpn
get arguemnt name: VYPRHK
get arguemnt retry: 10
get arguemnt interver: 30
Reconnect [VYPRHK] ... done
ERROR 1000: VPN cannot be connected.

The vpn connection is labeled VPN - VYPRHK
![image](https://user-images.githubusercontent.com/12408550/101016890-7e5c4780-35bd-11eb-9d65-c4088cdfe2a1.png)

I am also unable to locate the file called Find a file called connect_xxxxxxxx in the Openvpn directory ...has this changed.

Hoping you can help

**Comment by mrjackyliang** [comment]
Hi, you will need to run the script under `root` privileges, not `admin` privileges.

And also the Transmission directory seems wrong. It should not be under the Downloads folder.

**Comment by MartynWilliams** [comment]
Hi,
Thanks for the advice... I re-installed Transmission and got the script to work. The options to install / uninstall / start and stop work without errors. 
If I may I have two questions, 

1. There is a port-forwarding.css file included in your distribution, but it is not mentioned in your documentation. What purpose does it have and must I use it.

2. the script work perfectly when i use the start command, however when I run the repair script on a 5 minute cycle it stops th VPN . I think this is due to the fact that it sees that the port is closed. I have tested this and found that the port only closes when the VPN is running, if I stop the VPN and restart transmission the port is open

I'm aware the repair is mean to stop transmission from working when the VPN is not active, but the port check seems to be swapped.
Can you please help me understand what is going on here

Regards

**Comment by mrjackyliang** [comment]
Hi Martyn,

1. The `port-forwarding.php` file is used for detecting active port forwarding ports and is used by the `repair` section of the script. The reason why I built the port forwarding check was that a "particular VPN provider" that I use likes to often break my connections (if it's not breaking the internet check, they'll break the upload port to save bandwidth).

2. If you have defined a fixed upload port inside the script, you must also define the same upload port in Transmission and also in [VyprVPN](https://support.vyprvpn.com/hc/en-us/articles/360039668472-Does-VyprVPN-support-Port-Forwarding-). If you can, try not to use Transmission's default port.
